import os
from pathlib import Path
import shutil

"""
video_original_dir
|
|------ video_original
|------ analysis_dir (create_analysis_folder)
             |------- symlink to video_original (add_symlink) 
             |------- cropped_video (generated after ffmpeg)
             |------- h5 file (generated by dlc)
             |------- pickle (generated by dlc)
"""

def create_analysis_folder(path_to_video):
    pass

