import os
from pathlib import Path
import shutil

def key_dict_generater(case):
    case_key = {'animal_id': None, 'session': None, 'scan_idx': None}
    for ind, key in enumerate(case_key.keys()):
        case_key[key] = int(case.split('_')[ind])

    return case_key


def create_analysis_folder(case):
    """
    Input:
        case: string 
            a string that contains mouse id, session, and scan idx joined by underscores.
            ex) 20210_2_00015
    Return:
        None. this function creates the following directory structure:

        video_original_dir
        |
        |------ video_original
        |------ analysis_dir (create_analysis_folder)
                    |------- symlink to video_original (add_symlink) 
                    |------- cropped_video (generated after ffmpeg)
                    |------- h5 file (generated by dlc)
                    |------- pickle (generated by dlc)
    """
    case_dict = key_dict_generater(case)



